/**:
  ros__parameters:
    gait:
      knee_orientation : "><"
      pantograph_leg : false
      odom_scaler: 1.0
      max_linear_velocity_x : 1.0
      max_linear_velocity_y : 0.3
      max_angular_velocity_z : 1.5
      com_x_translation : 0.0
      swing_height : 0.03
      stance_depth : 0.0
      stance_duration : 0.35
      nominal_height : 0.48